<?php

namespace DavidUserBundle\Repository;

/**
 * RootRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RootRepository extends \Doctrine\ORM\EntityRepository
{
}
